# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  schedule:
  - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  GITHUB_WORKFLOW_TMP_FOLDER:   ".github-workflow-tmp"
  GITHUB_JSON:                  ${{ toJSON(github) }}
  SLACK_WEBHOOK_URL:            ${{ secrets.SLACK_WEBHOOK_URL }}
  DTC_RELEASE_CICD_KEY_BASE64:  ${{ secrets.DTC_RELEASE_CICD_KEY_BASE64 }}
  SF_DEVHUB_CLIENTID:           ${{ secrets.SF_DEVHUB_CLIENTID }}
  SF_DEVHUB_KEY_BASE64:         ${{ secrets.SF_DEVHUB_KEY_BASE64 }}
  SF_DEVHUB_ORG_URL:            ${{ secrets.SF_DEVHUB_ORG_URL }}
  SF_DEV2_AUTH_URL:              "force://PlatformCLI::5Aep861YbQ2WNspBqEUgFsHVTHaTaclYz2mONygu9Iyc.gICvY91IPR1qFRuHMq2Lie7iUST.FJWDGC.Q8pYbbn@va--squaredev2.my.salesforce.com"
  DEVHUB_ORG_USERNAME:          ${{ secrets.CICD_DEVHUB_USERNAME }}
  DEVHUB_ALIAS:                 "devhub"
  DEV2_ALIAS:                    "dev2"





# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: GET LATEST CI/CD SCRIPTS
        run: |
          echo "[1] CREATE SSH KEY"
          mkdir ~/.ssh
          echo "${{ secrets.DTC_RELEASE_CICD_KEY_BASE64 }}" | base64 -di > ~/.ssh/dtc-release-cicd.ssh  
          chmod 400 ~/.ssh/dtc-release-cicd.ssh  
          echo "[2] INITIALIZE SSH-AGENT"
          eval "$(ssh-agent -s)"
          echo "[3] ADD SSH KEY"
          ssh-add ~/.ssh/dtc-release-cicd.ssh
          echo "[4] REMOVE ./CI-CD DIRECTORY IF IT ALREADY EXISTS"
          rm -rf ci-cd
          git clone git@github.com:department-of-veterans-affairs/dtc-release-cicd.git -b master ci-cd

      - name: WORKFLOW SETUP
        run: pwsh ./ci-cd/workflow/workflow-setup.ps1

      - name: INSTALL SFDX 
        run: sh 'ci-cd/install/install-sfdx.sh'
        
      - name: AUTHENTICATE DEV2 ORG
        shell: pwsh
        run: . .\ci-cd\authenticate\authenticate-salesforce-authurl.ps1 -org_alias $env:DEV2_ALIAS -auth_url $env:SF_DEV2_AUTH_URL

      # Runs a single command using the runners shell
      - name: SOQL Query all error log records
        run: sfdx force:data:soql:query -q "SELECT Id FROM ACMN_Error_Log__c" --resultformat csv > out.csv

      # Runs a set of commands using the runners shell
      - name: Delete all error logs
        run: sfdx force:data:bulk:delete -s ACMN_Error_Log__c -f out.csv
