# This is a basic workflow to help you get started with Actions

name: SCHEDULED Squares Delete Error Logs

# Controls when the workflow will run
on: 
  schedule:
  - cron: '0 0 * * *'

env:
  GITHUB_WORKFLOW_TMP_FOLDER:   ".github-workflow-tmp"
  GITHUB_JSON:                  ${{ toJSON(github) }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  delete-error-logs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV2
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: INSTALL SFDX 
        run: npm install sfdx-cli --global
        
      - name: AUTHENTICATE DEV ORG
        shell: pwsh
        run: ../SQUARES-DevOps/.github/workflows/authenticate-salesforce-authurl.ps1  -auth_url ${{ secrets.AUTH_URL}}  -devhub_alias ${{ secrets.ALIAS}} 

      # Runs a single command using the runners shell
      - name: SOQL Query and delete all error log records
        shell: pwsh
        run: ../SQUARES-DevOps/.github/workflows/delete-error-logs.ps1 -username ${{ secrets.USERNAME}} 
        
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel

# This workflow contains a single job called "build"
  delete-error-logs-sit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: SIT
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: INSTALL SFDX 
        run: npm install sfdx-cli --global
        
      - name: AUTHENTICATE DEV ORG
        shell: pwsh
        run: ../SQUARES-DevOps/.github/workflows/authenticate-salesforce-authurl.ps1  -auth_url ${{ secrets.AUTH_URL}}  -devhub_alias ${{ secrets.ALIAS}} 

      # Runs a single command using the runners shell
      - name: SOQL Query and delete all error log records
        shell: pwsh
        run: ../SQUARES-DevOps/.github/workflows/delete-error-logs.ps1 -username ${{ secrets.USERNAME}} 
